workflows:
  localgo_android:
    name: LOCALGO Clean Android Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Generate Android project
        script: |
          flutter create . --platforms=android --org com.localgo --project-name localgo_customer
      - name: Get dependencies
        script: flutter pub get
      - name: Build clean APK
        script: flutter build apk --release
      - name: Build Google Play AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
