workflows:
  localgo_android:
    name: LOCALGO Clean Android
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
      - name: Build Play Store AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
